{
 "title": "NodeJS Dashboard Provisioned Copy",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(nodejs_version_info, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# Requests with Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"0.1\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 0.1s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"0.25\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 0.25s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"0.5\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 0.5s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"1\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 1s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"2.5\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 2.5s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"5\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 5s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"10\"}[$__rate_interval])) by (job)",
     "legendFormat": "Within 10s"
    }
   ]
  },
  {
   "title": "Percentage of Requests  with Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"0.1\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 0.1s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"0.25\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 0.25s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"0.5\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 0.5s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"1\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 1s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"2.5\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 2s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"5\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 5s"
    },
    {
     "expr": "sum(rate(nodejs_http_response_time_bucket{le=\"10\"}[20s])) / sum(rate(nodejs_http_response_time_count[20s]))",
     "legendFormat": "Within 10s"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(rate(nodejs_http_response_time_bucket{le=\"2.5\"}[5m])) by (job)\n+\n  sum(rate(nodejs_http_response_time_bucket{le=\"1\"}[5m])) by (job)\n) / 2 / sum(rate(nodejs_http_response_time_count[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count with Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nodejs_http_total_count{route=\"/fibonacci-slow/:num\"}[$__rate_interval])) by (code)",
     "legendFormat": "Slow {{code}}"
    },
    {
     "expr": "sum(rate(nodejs_http_total_count{route=\"/fibonacci/:num\"}[$__rate_interval])) by (code)",
     "legendFormat": "Fast {{code}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Fibonacci API - last Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "nodejs_http_total_duration{route=\"/fibonacci-slow/:num\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nodejs_http_total_duration{route=\"/fibonacci/:num\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}